"""Copy the studio's legal pages (Impressum, Datenschutz, AGB) 1:1 from the
WordPress source into src/data/legal/*.ts.

    python3 scripts/legal/import_legal.py

The text is taken verbatim. Only two kinds of change are made:

1. Markup is reduced to a whitelist of plain text tags (headings, paragraphs,
   lists, bold/italic, line breaks, links with href). Everything else,
   including scripts, styles, classes and inline attributes, is dropped, so
   the output is safe to render as HTML.
2. Domain fixes from the WordPress staging copy: the Hostinger staging
   hostname had replaced satuuu99.de (e.g. in the Impressum e-mail), and the
   AGB linked to another business's privacy policy. See REPLACEMENTS.
"""

import html
import json
import re
import subprocess
import sys
from html.parser import HTMLParser
from pathlib import Path

SOURCE = "https://lawngreen-cheetah-130579.hostingersite.com"
STAGING_HOST = "lawngreen-cheetah-130579.hostingersite.com"
OUT_DIR = Path(__file__).resolve().parents[2] / "src" / "data" / "legal"

# (source slug, output module, exported constant)
PAGES = [
    ("impressum", "impressum", "IMPRESSUM_HTML"),
    ("datenschutz", "datenschutz", "DATENSCHUTZ_HTML"),
    ("agbs", "agb", "AGB_HTML"),
]

# Applied in order; the most specific patterns come first.
REPLACEMENTS = [
    (f"https://{STAGING_HOST}/impressum/", "https://www.satuuu99.de/impressum"),
    (f"mailto:info@{STAGING_HOST}", "mailto:info@satuuu99.de"),
    (f"info@{STAGING_HOST}", "info@satuuu99.de"),
    (STAGING_HOST, "www.satuuu99.de"),
    ("https://nusumassage.de/datenschutz", "/datenschutz"),
]

ALLOWED = {"h1", "h2", "h3", "p", "ul", "ol", "li", "strong", "em", "a", "br"}
ALIASES = {"b": "strong", "i": "em", "h4": "h3", "h5": "h3", "h6": "h3"}
SKIPPED = {"script", "style", "svg", "noscript", "form", "button", "iframe"}
SAFE_HREF = re.compile(r"^(https?://|mailto:|tel:|/|#)", re.I)
SAFE_ID = re.compile(r"^[A-Za-z][A-Za-z0-9_-]{0,63}$")
HEADINGS = {"h1", "h2", "h3"}


class Sanitiser(HTMLParser):
    def __init__(self):
        super().__init__(convert_charrefs=True)
        self.out = []
        self.skip_depth = 0

    def handle_starttag(self, tag, attrs):
        if tag in SKIPPED:
            self.skip_depth += 1
            return
        tag = ALIASES.get(tag, tag)
        if self.skip_depth or tag not in ALLOWED:
            return
        if tag == "br":
            self.out.append("<br>")
        elif tag in HEADINGS and SAFE_ID.match(dict(attrs).get("id") or ""):
            # Keep heading ids so the in-page table of contents still works.
            self.out.append(f'<{tag} id="{dict(attrs)["id"]}">')
        elif tag == "a":
            href = dict(attrs).get("href") or ""
            safe = href if SAFE_HREF.match(href) else "#"
            self.out.append(f'<a href="{html.escape(safe, quote=True)}">')
        else:
            self.out.append(f"<{tag}>")

    def handle_endtag(self, tag):
        if tag in SKIPPED:
            self.skip_depth = max(0, self.skip_depth - 1)
            return
        tag = ALIASES.get(tag, tag)
        if self.skip_depth or tag not in ALLOWED or tag == "br":
            return
        self.out.append(f"</{tag}>")

    def handle_data(self, data):
        if not self.skip_depth:
            self.out.append(html.escape(data, quote=False))


def fetch(slug):
    # curl uses the system trust store; python.org builds on macOS often ship
    # without CA certificates, which breaks urllib's TLS verification.
    result = subprocess.run(
        ["curl", "-sSfL", "--max-time", "30", f"{SOURCE}/{slug}/"],
        capture_output=True,
        check=False,
    )
    if result.returncode != 0:
        raise RuntimeError(f"{slug}: {result.stderr.decode().strip()}")
    return result.stdout.decode("utf-8")


def sanitise(page_html, slug):
    main = re.search(r"<main\b.*?</main>", page_html, re.S)
    if not main:
        raise RuntimeError(f"{slug}: no <main> element found")
    parser = Sanitiser()
    parser.feed(main.group(0))
    text = re.sub(r"\s+", " ", "".join(parser.out))
    for _ in range(3):
        text = re.sub(r"<(p|strong|em|li|h[1-3])(?: id=\"[^\"]*\")?>\s*</\1>", "", text)
    text = re.sub(r"\s*(</?(?:p|ul|ol|li|h[1-3])(?: id=\"[^\"]*\")?>)\s*", r"\1", text)
    # The page title is rendered by the React page itself.
    text = re.sub(r"^<h1[^>]*>.*?</h1>", "", text.strip())
    for old, new in REPLACEMENTS:
        text = text.replace(old, new)
    if STAGING_HOST in text:
        raise RuntimeError(f"{slug}: staging host still present")
    return text


def main():
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    for slug, module, constant in PAGES:
        body = sanitise(fetch(slug), slug)
        target = OUT_DIR / f"{module}.ts"
        target.write_text(
            "// Generated by scripts/legal/import_legal.py from "
            f"{SOURCE}/{slug}/\n"
            "// Do not edit by hand; change the source page and re-run.\n"
            f"export const {constant} =\n  {json.dumps(body, ensure_ascii=False)};\n",
            encoding="utf-8",
        )
        print(f"Wrote {target.relative_to(OUT_DIR.parents[2])} ({len(body)} chars)")


if __name__ == "__main__":
    try:
        main()
    except Exception as error:  # surface a readable message, non-zero exit
        print(f"Legal import failed: {error}", file=sys.stderr)
        sys.exit(1)
